import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
//import { Post } from "@prisma/client";
import Head from "next/head";
//import Link from "next/link";
import { api } from "~/utils/api";
//todo fix envs
interface Post {
  id: string;
  createdAt: Date; // Adjusted to Date type based on DateTime in your schema
  content: string;
  authorId: string;
}

const CreatePostWizard = () => {
  const {user} = useUser();

  if  (!user) return null;


  return ( <div className="flex w-full gap-3 ">
    <img src={user.profileImageUrl}
     alt="Profile image" 
     className="w-14 h-14 rounded-full" />
    <input placeholder="Type a message!"  className="grow bg-transparent outline-none" />
  </div>

  );
}




export default function Home() {
  //const hello = api.post.hello.useQuery({ text: "from tRPC" });

  const user = useUser();

  const {data} = api.posts.getAll.useQuery();
 

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
        <div className="flex border-b border-slate-400 p-4">
          <div>{!user && <div className="flex-justify-center"><SignInButton/></div>}{!!user && <CreatePostWizard/>}</div>
        </div>
        <div className="flex flex-col">
        {(data as Post[] | undefined)?.map((post) => (
        <div key={post.id} className="p-8 border-b border-slate-400">{post.content}</div>
      ))}
        </div>
        </div>
      </main>
    </>
  );
}
